const LAYOUT__HEADER__NAV_BAR_HEIGHT = 70;

const PAGES__CHAT__CHAT_SEARCH = 52;

const PAGES__CHAT__SIDE_BAR_CHAT = `calc(100% - ${LAYOUT__HEADER__NAV_BAR_HEIGHT + PAGES__CHAT__CHAT_SEARCH}px)`

export {
    LAYOUT__HEADER__NAV_BAR_HEIGHT,
    PAGES__CHAT__CHAT_SEARCH,
    PAGES__CHAT__SIDE_BAR_CHAT
};